version: "3.1"

services:
  server:
    image: node
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "nodemon server.js"
    ports:
      - 8080:8080
    depends_on:
      - mongo
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env # For SLACK_BOT_ACCESS_TOKEN
    environment:
      NODE_ENV: development
      PORT: 8080
      MONGODB_URI: "mongodb://mongo:27017/thanksbot"

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
