version: "3.1"

services:
  server:
    image: docker-node-mongo
    build: .
    command: "node server.js"
    ports:
      - 8080:8080
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always

  mongo-express:
    links:
      - mongo
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpress
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpress
